version: "3"

services:
  jenkins:
    build:
      context: ./jenkins
    ports:
      - "8080:8080"
    networks:
      - stack-ci
    volumes:
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - stack-ci
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - stack-ci
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  stack-ci:
    driver: bridge

volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data: